### ISSUE TITLE
创建一个可扩展的“圆”组件

### ISSUE THREAD

**Issue by waite1x** [freebeDAO/advanture-island#4]
将“圆”看作为一个可扩展组件，圆可在一个无线大的平面或立体空间中移动，支持为外部为其添加各种功能，视扩展功能的难易程度给定相应经验值，例如：
1. 可自动移动：可以设置速度、方向、快捷键等
2. 鼠标点击，移动到指定位置，具有移动动画
3. 记录位置，保存到数据库中，关联用户，下次打开时定位到上次位置
4. 其他行为，如跳跃、旋转等

遇到好的“圆“的可扩展组件，考虑合并到主分支，作为公共基础组件，再派生出各种任务。

**Comment by i5possible** [comment]
圆是 UI 组件吧，操作、行为和 UI 应该是正交的，通过组合实现即可，数据记录、关联是数据层面，这三部分应该都是相互独立，最后组合即可
